#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from open_freedom_rides import journey_segments_for_rider, load_dataset

RAW = ROOT / "data" / "raw" / "pilot"
DERIVED = ROOT / "data" / "derived" / "pilot"
GENERATED = ROOT / "assets" / "generated" / "pilot"


def build_geojson() -> dict:
    dataset = load_dataset(RAW)
    locations_by_id = {location["id"]: location for location in dataset.locations}

    features: list[dict] = []

    for rider in dataset.riders:
        segments = journey_segments_for_rider(dataset, rider["id"])
        if not segments:
            continue

        for segment in segments:
            features.append(
                {
                    "type": "Feature",
                    "properties": {
                        "feature_type": "route_segment",
                        "segment_id": segment["segment_id"],
                        "rider_id": segment["rider_id"],
                        "from_event_id": segment["from_event_id"],
                        "to_event_id": segment["to_event_id"],
                    },
                    "geometry": {
                        "type": "LineString",
                        "coordinates": [segment["from"], segment["to"]],
                    },
                }
            )

    for event in dataset.events:
        location = locations_by_id.get(event["location_id"])
        if not location:
            continue
        features.append(
            {
                "type": "Feature",
                "properties": {
                    "feature_type": "event_node",
                    "event_id": event["id"],
                    "event_type": event["event_type"],
                    "date": event["date"],
                    "location_id": event["location_id"],
                    "rider_ids": event.get("rider_ids", []),
                    "source_refs": event.get("source_refs", []),
                },
                "geometry": {
                    "type": "Point",
                    "coordinates": [location["longitude"], location["latitude"]],
                },
            }
        )

    return {"type": "FeatureCollection", "features": features}


def lonlat_to_xy(lon: float, lat: float, bbox: tuple[float, float, float, float]) -> tuple[float, float]:
    min_lon, min_lat, max_lon, max_lat = bbox
    width = 1000
    height = 600
    x = ((lon - min_lon) / (max_lon - min_lon)) * width if max_lon != min_lon else width / 2
    y = height - (((lat - min_lat) / (max_lat - min_lat)) * height if max_lat != min_lat else height / 2)
    return (x, y)


def build_svg(geojson: dict) -> str:
    coords = [
        feature["geometry"]["coordinates"]
        for feature in geojson["features"]
        if feature["geometry"]["type"] == "Point"
    ]
    lons = [coord[0] for coord in coords]
    lats = [coord[1] for coord in coords]
    bbox = (min(lons), min(lats), max(lons), max(lats))

    lines: list[str] = []
    for feature in geojson["features"]:
        if feature["geometry"]["type"] == "LineString":
            start, end = feature["geometry"]["coordinates"]
            x1, y1 = lonlat_to_xy(start[0], start[1], bbox)
            x2, y2 = lonlat_to_xy(end[0], end[1], bbox)
            lines.append(
                f'<line x1="{x1:.2f}" y1="{y1:.2f}" x2="{x2:.2f}" y2="{y2:.2f}" stroke="#b11f24" stroke-width="3" opacity="0.8" />'
            )

    points: list[str] = []
    for feature in geojson["features"]:
        if feature["geometry"]["type"] == "Point":
            lon, lat = feature["geometry"]["coordinates"]
            x, y = lonlat_to_xy(lon, lat, bbox)
            points.append(
                f'<circle cx="{x:.2f}" cy="{y:.2f}" r="5" fill="#1f3a93" />'
            )

    return "\n".join(
        [
            '<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="600" viewBox="0 0 1000 600">',
            '<rect x="0" y="0" width="1000" height="600" fill="#f8f8f8" />',
            '<text x="20" y="30" font-size="20" font-family="sans-serif">Freedom Rides Pilot Journey Map</text>',
            *lines,
            *points,
            "</svg>",
        ]
    )


def build_commons_wikitext() -> str:
    return "\n".join(
        [
            "== Summary ==",
            "Freedom Rides pilot map generated from source-cited event data.",
            "",
            "== Licensing ==",
            "{{CC-BY-SA-4.0}}",
            "",
            "== Source ==",
            "Generated by Open Freedom Rides Mapping pipeline.",
        ]
    )


def main() -> int:
    DERIVED.mkdir(parents=True, exist_ok=True)
    GENERATED.mkdir(parents=True, exist_ok=True)

    geojson = build_geojson()
    (DERIVED / "rider_journeys.geojson").write_text(json.dumps(geojson, indent=2), encoding="utf-8")

    svg = build_svg(geojson)
    (GENERATED / "freedom_rides_pilot.svg").write_text(svg, encoding="utf-8")

    commons_wikitext = build_commons_wikitext()
    (GENERATED / "freedom_rides_pilot.commons.wikitext").write_text(commons_wikitext, encoding="utf-8")

    print("Build completed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
